import type { CollectionConfig } from '@sonicjs-cms/core';

export default {
  name: 'jobs',
  displayName: 'Jobs',
  slug: 'jobs',
  description: 'Manage job postings for Istanbul',
  icon: '💼',

  schema: {
    type: 'object',
    properties: {
      title_ar: {
        type: 'string',
        title: 'Job Title (Arabic)',
        required: true,
        maxLength: 200,
      },
      title_en: {
        type: 'string',
        title: 'Job Title (English)',
        required: true,
        maxLength: 200,
      },
      title_tr: {
        type: 'string',
        title: 'Job Title (Turkish)',
        required: true,
        maxLength: 200,
      },
      slug: {
        type: 'slug',
        title: 'URL Slug',
        required: true,
        maxLength: 200,
      },
      description_ar: {
        type: 'textarea',
        title: 'Description & Requirements (Arabic)',
        required: true,
      },
      description_en: {
        type: 'textarea',
        title: 'Description & Requirements (English)',
        required: true,
      },
      description_tr: {
        type: 'textarea',
        title: 'Description & Requirements (Turkish)',
        required: true,
      },
      company: {
        type: 'reference',
        collection: 'companies',
        title: 'Hiring Company',
        required: true,
      },
      category: {
        type: 'reference',
        collection: 'categories',
        title: 'Job Category',
        required: true,
      },
      location_ar: {
        type: 'string',
        title: 'Location / District (Arabic, e.g. الفاتح)',
        required: true,
        maxLength: 100,
      },
      location_en: {
        type: 'string',
        title: 'Location / District (English, e.g. Fatih)',
        required: true,
        maxLength: 100,
      },
      location_tr: {
        type: 'string',
        title: 'Location / District (Turkish, e.g. Fatih)',
        required: true,
        maxLength: 100,
      },
      jobType: {
        type: 'select',
        title: 'Job Type',
        required: true,
        enum: ['full-time', 'part-time', 'remote', 'internship'],
        enumLabels: ['Full Time', 'Part Time', 'Remote', 'Internship'],
      },
      salary: {
        type: 'string',
        title: 'Salary Range (e.g. 20,000 - 30,000 TL)',
        required: false,
      },
      applyLink: {
        type: 'url',
        title: 'Application Link (URL)',
        required: false,
      },
      applyEmail: {
        type: 'email',
        title: 'Application Email',
        required: false,
      },
      language: {
        type: 'select',
        title: 'Required Language',
        required: true,
        enum: ['ar', 'en', 'both'],
        enumLabels: ['Arabic', 'English', 'Both / Bilingual'],
      },
      featured: {
        type: 'boolean',
        title: 'Featured Post?',
        default: false,
      },
      guestEmail: {
        type: 'email',
        title: 'Guest Submitter Email (Internal)',
        required: false,
      },
      publishedAt: {
        type: 'datetime',
        title: 'Publish Date',
        required: false,
      },
      phone: {
        type: 'string',
        title: 'Employer Phone / Contact Number',
        required: false,
        maxLength: 50,
      },
      status: {
        type: 'select',
        title: 'Status',
        required: true,
        enum: ['draft', 'published', 'archived'],
        enumLabels: ['Draft', 'Published', 'Archived'],
        default: 'draft',
      },
      screeningQuestionsJson: {
        type: 'textarea',
        title: 'Screening Questions (JSON Array)',
        required: false,
      },
      transitLine: {
        type: 'select',
        title: 'Transit Line Near Workspace',
        required: false,
        enum: ['none', 'm2', 'metrobus', 'm4', 'm11'],
        enumLabels: ['None', 'M2 Metro Line', 'Metrobus Line', 'M4 Metro Line', 'M11 Airport Metro'],
        default: 'none',
      },
      imageUrl: {
        type: 'string',
        title: 'Job Header Image URL',
        required: false,
      },
      seoKeywords: {
        type: 'textarea',
        title: 'SEO Keywords (JSON Array or Comma Separated)',
        required: false,
      },
      seoDescription: {
        type: 'textarea',
        title: 'SEO Meta Description',
        required: false,
      },
    },
    required: [
      'title_ar',
      'title_en',
      'title_tr',
      'slug',
      'description_ar',
      'description_en',
      'description_tr',
      'company',
      'category',
      'location_ar',
      'location_en',
      'location_tr',
      'jobType',
      'language',
      'status',
    ],
  },

  listFields: ['title_en', 'company', 'category', 'status', 'publishedAt'],
  searchFields: ['title_en', 'title_ar', 'title_tr', 'description_en', 'description_ar', 'description_tr', 'location_en', 'location_ar', 'location_tr'],
  defaultSort: 'publishedAt',
  defaultSortOrder: 'desc',

  managed: true,
  isActive: true,
  cache: {
    enabled: true,
    ttl: 60,
  },
} satisfies CollectionConfig;
